### PR TITLE
rm wait_while_speaking

### PR DESCRIPTION
**Pull request by JarbasAl**
usage here seems intended for mk1 faceplate, this should be handled in mk1 specific integration  (TODO - mk1 gui extension)

### CODE REVIEW

**Comment by emphasize** [comment]
and since they want it extra safe, they put a sleep in front 😛

**Comment by mikejgray** [comment]
Is this a breaking change for Mark 1? I know there aren't a ton of them out there, but it would be good to indicate that to them until the code has been refactored to PHAL.

**Review by builderjer — APPROVED** [review]
This works for me, but the issue that @mikejgray brought up about a breaking change for a mk1 should be addressed.  I do not have one to test on, but none the less, it should at least be noted.

**Comment by JarbasAl** [comment]
the mk1 support is not removed from the skill, the bus messages for it are still emitted

but since ovos never officially supported mk1 this is not really an issue, we never had an image for it, so for all intent and purposes the mk1 is a target platform but not a supported one yet, it is still classic core

we did get our hands in a few mk1s from our fundraiser, so official support is coming!

**Pull request merged**
